### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by aleeeee1** [ProjectInfinity-X/official_devices#105] opened 2024-08-03 17:50 UTC
### Device you want to apply for

Xiaomi Mi A3 (laurel_sprout)

### Device Tree Sources

https://github.com/aleeeee1/device_xiaomi_laurel_sprout dt
https://github.com/aleeeee1/vendor_xiaomi_laurel_sprout vendor
https://github.com/aleeeee1/device_xiaomi_laurel_sprout-kernel (kernel is prebuilt)

### Number of rom(s) you maintain, also name them stating official or unofficial

1, Blaze UNOFFICIAL.

### Any Exceptions/special concern?

I need to apply some patches to make the rom work with my device.
[build_make](https://github.com/aleeeee1/build_make-blaze/commit/fb1b0a18c66952c6f04929215cecb8c357b3a52d)
[tinycompass](https://github.com/aleeeee1/android_external_tinycompress/commit/4dc972f471802ed2931ef650398b2d7fe8c71ab5)
[gralloc, in qcom-caf/sm8150/display](https://github.com/Pos-trinket/hardware_qcom_display/commit/12c2d06c4c59c4f521c5a993c4aa8f628e0549ab)

probably something else i will face at build time

I'm having some issues with my trees, so the build will have some issues with dt2w and with notifiations LED.

### Telegram username / or any alternative medium to reach you

bakkaq

### GitHub username

aleeeee1

**Comment by tejas101k** [comment] 2024-08-03 18:27
How come you still have bugged dt2w and prebuilt kernel on such a old well developed piece like trinket?

**Comment by aleeeee1** [comment] 2024-08-03 20:16
> How come you still have bugged dt2w and prebuilt kernel on such a old well developed piece like trinket?

I'm not sure, i have the powerhint commits and whatever i've seen other devices do, but since i nuked the power hal extension, it just never got to work again.

**Comment by aleeeee1** [comment] 2024-08-04 08:46
> How come you still have bugged dt2w and prebuilt kernel on such a old well developed piece like trinket?

Sorry but I completely missed the prebuilt kernel thing.
We have some opensource kernel, but they're not very good comparing, for example bb, and they're missing some features, like usb otg and so on.
Due to some community drama (people stealing other's work), the maintainers decided to close everything and so, I'm left with the prebuilt images... awesome, isn't it?

**Comment by tejas101k** [comment] 2024-08-04 12:52
> > How come you still have bugged dt2w and prebuilt kernel on such a old well developed piece like trinket?
> 
> I'm not sure, i have the powerhint commits and whatever i've seen other devices do, but since i nuked the power hal extension, it just never got to work again.

are you sure you using correct node for trinket?
https://github.com/aleeeee1/device_xiaomi_laurel_sprout/commit/37c44859354ca551daf15b3671854e4f8b8264a0#diff-217385f1bdd67cd5ef1286b69d86734243cb52a0bf9db180fb8028f44cf872fbR181

**Comment by aleeeee1** [comment] 2024-08-04 13:07
> > > How come you still have bugged dt2w and prebuilt kernel on such a old well developed piece like trinket?
> > 
> > 
> > I'm not sure, i have the powerhint commits and whatever i've seen other devices do, but since i nuked the power hal extension, it just never got to work again.
> 
> are you sure you using correct node for trinket? [aleeeee1/device_xiaomi_laurel_sprout@37c4485#diff-217385f1bdd67cd5ef1286b69d86734243cb52a0bf9db180fb8028f44cf872fbR181](https://github.com/aleeeee1/device_xiaomi_laurel_sprout/commit/37c44859354ca551daf15b3671854e4f8b8264a0#diff-217385f1bdd67cd5ef1286b69d86734243cb52a0bf9db180fb8028f44cf872fbR181)

yes, if you take a look at other devices trees of laurel_sprout (and probably mine too if you dig in the history), you can see that `TARGET_TAP_TO_WAKE_NODE` in the past, had the value of `/dev/input/event2`.
That should be it :)

**Comment by tejas101k** [comment] 2024-08-04 18:32
I apologize for not being able to accommodate you and for the delay in addressing your concerns on this forum. However, something as crucial as dt2w needs to be fully functional for the official status. 

The issue is compounded by the fact that, despite having proper proprietary and kernel support, it fails to function correctly after the implementation of the common `libperfmgr`. I believe this issue is very much fixable, just a proper extension hal fabrication is needed.

You should consider implementing it as a libperfmgr hal extension, ensuring that the required cpp hal needed here is maintained according to your device.

Closing it as of now. Feel free to apply again [obviously only if you want to :)] once you fix your issues.

**Closed** 2024-08-04 18:32 UTC

**Comment by aleeeee1** [comment] 2024-08-19 17:58
i managed to fix dt2w after tons of trying i just decided to revert the commit of common libperfmgr.

**Comment by tejas101k** [comment] 2024-08-19 18:57
https://github.com/ProjectInfinity-X/.github/blob/main/profile/README.mkdn?plain=1#L19

Refer to new conditions.
Release one unofficial functional build with fixable issues solved.
Once conditions achieved, Reapply with opening fresh new issue.
