### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Musafir02** [ProjectInfinity-X/official_devices#239] opened 2024-12-16 18:07 UTC
### Device you want to apply for

Redmi note 10 pro (sweet/sweetin)

### Device Tree Sources

https://github.com/Musafir02/device_xiaomi_sweet.git

### Number of rom(s) you maintain, also name them stating official or unofficial

1 unofficial 

### Link to your one released Infinity-X Unofficial Build (must be a link of a platform eg. telegram or xda)

https://t.me/RoyalOSsweet/93

### Any Exceptions/special concern?

I would like to work with you.

### Telegram username / or any alternative medium to reach you

@Musafir1875

### GitHub username

Musafir02

**Comment by tejas101k** [comment] 2024-12-16 18:32
Closing since duplicate of #238

**Closed by tejas101k** 2024-12-16 18:32 UTC
